
# All the settings for each command
commands:
  get:
    name: 'get'
    disabled: true
    subcommands:
      sword:
        name: 'stick'
        hidden: false
        disabled: true
        new-commands: 
        - 'give %player% stick 1'
  kit:
    name: 'kit|kits'
    disabled: true
    hide-sub: true
    hidden: true
    disable-sub: true