
commands:
  adminkit:
    name: 'kit|kits'
    permission: 'customcrates.admin'
    disabled: true
    new-commands: 
    - 'crate virtualcrates'
    subcommands:
      list:
        name: 'list'
        hidden: false
        disabled: true
        new-commands: 
        - 'crate virtualcrates'
  kit:
    name: 'kit|kits'
    disabled: true
    hide-sub: true
    new-commands: 
    - 'crates'
    subcommands:
      list:
        name: 'list'
        hidden: false
        disabled: true
        new-commands: 
        - 'crates'
      claim:
        name: 'claim'
        hidden: false
        disabled: true
        server: true
        new-commands: 
        - 'crate open Claim %sender%'
      slimefun:
        name: 'slimefun'
        hidden: false
        disabled: true
        server: true
        new-commands: 
        - 'crate open Slimefun %sender%'
      tools:
        name: 'tools|tool'
        hidden: false
        disabled: true
        server: true
        new-commands: 
        - 'crate open Tools %sender%'
      daily:
        name: 'daily'
        hidden: false
        disabled: true
        server: true
        new-commands: 
        - 'crate open Daily %sender%'
      better-tools:
        name: 'better_tools'
        hidden: false
        disabled: true
        server: true
        new-commands: 
        - 'crate open Better_Tools %sender%'